    #ifndef REPLIES_H
	# define REPLIES_H

	# include <iostream>	
	
	class Replies {

		public :

			Replies(void) {};
			~Replies(void) {};
 
			/* "001" */ std::string RPL_WELCOME() { return (":server 001 <nick> :Welcome to the <network> Network, <nick>[!<user>@<host>]\n"); };
			/* "002" */ std::string RPL_YOURHOST() { return (":Your host is <servername>, running version <version>"); };
			/* "003" */ std::string RPL_CREATED() { return (":This server was created <date>"); };
			/* "004" */ std::string RPL_MYINFO() { return ("<server_name> <version> <user_modes> <chan_modes>"); };
			/* "005" */ std::string RPL_BOUNCE() { return ("<server_name> <version> <user_modes> <chan_modes> <channel_modes_with_params> <user_modes_with_params> <server_modes> <server_modes_with_params>"); };
			/* "043" */ std::string RPL_SAVENICK() { return (":<info>"); };
			/* "200" */ std::string RPL_TRACELINK() { return ("Link <version>[.<debug_level>] <destination> <next_server> [V<protocol_version> <link_uptime_in_seconds> <backstream_sendq> <upstream_sendq>]"); };
			/* "201" */ std::string RPL_TRACECONNECTING() { return ("Try. <class> <server>"); };
			/* "202" */ std::string RPL_TRACEHANDSHAKE() { return ("H.S. <class> <server>"); };
			/* "203" */ std::string RPL_TRACEUNKNOWN() { return ("???? <class> [<connection_address>]"); };
			/* "204" */ std::string RPL_TRACEOPERATOR() { return ("Oper <class> <nick>"); };
			/* "205" */ std::string RPL_TRACEUSER() { return ("User <class> <nick>"); };
			/* "206" */ std::string RPL_TRACESERVER() { return ("Serv <class> <int>S <int>C <server> <nick!user|*!*>@<host|server> [V<protocol_version>]"); };
			/* "207" */ std::string RPL_TRACESERVICE() { return ("Service <class> <name> <type> <active_type>"); };
			/* "208" */ std::string RPL_TRACENEWTYPE() { return ("<newtype> 0 <client_name>"); };
			/* "209" */ std::string RPL_TRACECLASS() { return ("Class <class> <count>"); };
			/* "211" */ std::string RPL_STATSLINKINFO() { return ("<linkname> <sendq> <sent_msgs> <sent_bytes> <recvd_msgs> <rcvd_bytes> <time_open>"); };
			/* "212" */ std::string RPL_STATSCOMMANDS() { return ("<command> <count> [<byte_count> <remote_count>]"); };
			/* "213" */ std::string RPL_STATSCLINE() { return ("C <host> * <name> <port> <class>"); };
			/* "214" */ std::string RPL_STATSNLINE() { return ("N <host> * <name> <port> <class>"); };
			/* "215" */ std::string RPL_STATSILINE() { return ("I <host> * <host> <port> <class>"); };
			/* "216" */ std::string RPL_STATSKLINE() { return ("K <host> * <username> <port> <class>"); };
			/* "218" */ std::string RPL_STATSYLINE() { return ("Y <class> <ping_freq> <connect_freq> <max_sendq>"); };
			/* "219" */ std::string RPL_ENDOFSTATS() { return ("<query> :<info>"); };
			/* "221" */ std::string RPL_UMODEIS() { return ("<user_modes> [<user_mode_params>]"); };
			/* "234" */ std::string RPL_SERVLIST() { return ("<name> <server> <mask> <type> <hopcount> <info>"); };
			/* "235" */ std::string RPL_SERVLISTEND() { return ("<mask> <type> :<info>"); };
			/* "241" */ std::string RPL_STATSLLINE() { return ("L <hostmask> * <servername> <maxdepth>"); };
			/* "242" */ std::string RPL_STATSUPTIME() { return (":Server Up <days> days <hours>:<minutes>:<seconds>"); };
			/* "243" */ std::string RPL_STATSOLINE() { return ("O <hostmask> * <nick> [:<info>]"); };
			/* "244" */ std::string RPL_STATSHLINE() { return ("H <hostmask> * <servername>"); };
			/* "251" */ std::string RPL_LUSERCLIENT() { return (":There are <int> users and <int> invisible on <int> servers"); };
			/* "252" */ std::string RPL_LUSEROP() { return ("<int> :<info>"); };
			/* "253" */ std::string RPL_LUSERUNKNOWN() { return ("<int> :<info>"); };
			/* "254" */ std::string RPL_LUSERCHANNELS() { return ("<int> :<info>"); };
			/* "255" */ std::string RPL_LUSERME() { return (":I have <int> clients and <int> servers"); };
			/* "256" */ std::string RPL_ADMINME() { return ("<server> :<info>"); };
			/* "257" */ std::string RPL_ADMINLOC1() { return (":<admin_location>"); };
			/* "258" */ std::string RPL_ADMINLOC2() { return (":<admin_location>"); };
			/* "259" */ std::string RPL_ADMINEMAIL() { return (":<email_address>"); };
			/* "261" */ std::string RPL_TRACELOG() { return ("File <logfile> <debug_level>"); };
			/* "262" */ std::string RPL_TRACEEND() { return ("<server_name> <version>[.<debug_level>] :<info>"); };
			/* "263" */ std::string RPL_TRYAGAIN() { return ("<command> :<info>"); };
			/* "301" */ std::string RPL_AWAY() { return ("<nick> :<message>"); };
			/* "302" */ std::string RPL_USERHOST() { return (":*1<reply> *( ' ' <reply> ) return"); };
			/* "303" */ std::string RPL_ISON() { return (":*1<nick> *( ' ' <nick> ) return"); };
			/* "305" */ std::string RPL_UNAWAY() { return (":<info>"); };
			/* "306" */ std::string RPL_NOWAWAY() { return (":<info>"); };
			/* "311" */ std::string RPL_WHOISUSER() { return ("<nick> <user> <host> * :<real_name>"); };
			/* "312" */ std::string RPL_WHOISSERVER() { return ("<nick> <server> :<server_info>"); };
			/* "313" */ std::string RPL_WHOISOPERATOR() { return ("<nick> :<privileges>"); };
			/* "314" */ std::string RPL_WHOWASUSER() { return ("<nick> <user> <host> * :<real_name>"); };
			/* "315" */ std::string RPL_ENDOFWHO() { return ("<name> :<info>"); };
			/* "317" */ std::string RPL_WHOISIDLE() { return ("<nick> <seconds> :seconds idle"); };
			/* "318" */ std::string RPL_ENDOFWHOIS() { return ("<nick> :<info>"); };
			/* "319" */ std::string RPL_WHOISCHANNELS() { return ("<nick> :*( ( '@' / '+' ) return <channel> ' ' ) return"); };
			/* "321" */ std::string RPL_LISTSTART() { return ("Channels :Users Name"); };
			/* "322" */ std::string RPL_LIST() { return ("<channel> <#_visible> :<topic>"); };
			/* "323" */ std::string RPL_LISTEND() { return (":<info>"); };
			/* "324" */ std::string RPL_CHANNELMODEIS() { return ("<channel> <mode> <mode_params>"); };
			/* "325" */ std::string RPL_UNIQOPIS() { return ("<channel> <nickname>"); };
			/* "331" */ std::string RPL_NOTOPIC() { return ("<channel> :<info>"); };
			/* "332" */ std::string RPL_TOPIC() { return ("<channel> :<topic>"); };
			/* "341" */ std::string RPL_INVITING() { return ("<nick> <channel>"); };
			/* "342" */ std::string RPL_SUMMONING() { return ("<user> :<info>"); };
			/* "345" */ std::string RPL_ENDOFREOPLIST() { return ("<channel> <user being invited> <user issuing invite> :<user being invited> has been invited by <user issuing invite>"); };
			/* "346" */ std::string RPL_INVITELIST() { return ("<channel> <invitemask>"); };
			/* "347" */ std::string RPL_ENDOFINVITELIST() { return ("<channel> :<info>"); };
			/* "348" */ std::string RPL_EXCEPTLIST() { return ("<channel> <exceptionmask>"); };
			/* "349" */ std::string RPL_ENDOFEXCEPTLIST() { return ("channel> :<info>"); };
			/* "351" */ std::string RPL_VERSION() { return ("<version>[.<debuglevel>] <server> :<comments>"); };
			/* "352" */ std::string RPL_WHOREPLY() { return ("<channel> <user> <host> <server> <nick> <H|G>[*][@|+] :<hopcount> <real_name>"); };
			/* "353" */ std::string RPL_NAMREPLY() { return ("( '=' / '*' / '@' ) return <channel> ' ' : [ '@' / '+' ] <nick> *( ' ' [ '@' / '+' ] <nick> ) return"); };
			/* "364" */ std::string RPL_LINKS() { return ("<mask> <server> :<hopcount> <server_info>"); };
			/* "365" */ std::string RPL_ENDOFLINKS() { return ("<mask> :<info>"); };
			/* "366" */ std::string RPL_ENDOFNAMES() { return ("<channel> :<info>"); };
			/* "367" */ std::string RPL_BANLIST() { return ("<channel> <banid> [<time_left> :<reason>]"); };
			/* "368" */ std::string RPL_ENDOFBANLIST() { return ("<channel> :<info>"); };
			/* "369" */ std::string RPL_ENDOFWHOWAS() { return ("<nick> :<info>"); };
			/* "371" */ std::string RPL_INFO() { return (":<string>"); };
			/* "372" */ std::string RPL_MOTD() { return (":- <string>"); };
			/* "374" */ std::string RPL_ENDOFINFO() { return (":<info>"); };
			/* "375" */ std::string RPL_MOTDSTART() { return (":- <server> Message of the day -"); };
			/* "376" */ std::string RPL_ENDOFMOTD() { return (":End of /MOTD command"); };
			/* "381" */ std::string RPL_YOUREOPER() { return (":<info>"); };
			/* "382" */ std::string RPL_REHASHING() { return ("<config_file> :<info>"); };
			/* "383" */ std::string RPL_YOURESERVICE() { return (":You are service <service_name>"); };
			/* "391" */ std::string RPL_TIME() { return ("<server> :<time string>"); };
			/* "392" */ std::string RPL_USERSSTART() { return (":UserID Terminal Host"); };
			/* "393" */ std::string RPL_USERS() { return (":<username> <ttyline> <hostname>"); };
			/* "394" */ std::string RPL_ENDOFUSERS() { return (":<info>"); };
			/* "395" */ std::string RPL_NOUSERS() { return (":<info>"); };
			/* "401" */ std::string ERR_NOSUCHNICK() { return ("<nick> :<reason>"); };
			/* "402" */ std::string ERR_NOSUCHSERVER() { return ("<server> :<reason>"); };
			/* "403" */ std::string ERR_NOSUCHCHANNEL() { return ("<channel> :<reason>"); };
			/* "404" */ std::string ERR_CANNOTSENDTOCHAN() { return ("<channel> :<reason>"); };
			/* "405" */ std::string ERR_TOOMANYCHANNELS() { return ("<channel> :<reason>"); };
			/* "406" */ std::string ERR_WASNOSUCHNICK() { return ("<nick> :<reason>"); };
			/* "407" */ std::string ERR_TOOMANYTARGETS() { return ("<target> :<reason>"); };
			/* "408" */ std::string ERR_NOSUCHSERVICE() { return ("<service_name> :<reason>"); };
			/* "409" */ std::string ERR_NOORIGIN() { return (":<reason>"); };
			/* "411" */ std::string ERR_NORECIPIENT() { return (":<reason>"); };
			/* "412" */ std::string ERR_NOTEXTTOSEND() { return (":<reason>"); };
			/* "413" */ std::string ERR_NOTOPLEVEL() { return ("<mask> :<reason>"); };
			/* "414" */ std::string ERR_WILDTOPLEVEL() { return ("<mask> :<reason>"); };
			/* "415" */ std::string ERR_BADMASK() { return ("<mask> :<reason>"); };
			/* "416" */ std::string ERR_TOOMANYMATCHES() { return ("<command> [<mask>] :<info>"); };
			/* "421" */ std::string ERR_UNKNOWNCOMMAND() { return ("<command> :<reason>"); };
			/* "422" */ std::string ERR_NOMOTD() { return (":<reason>"); };
			/* "423" */ std::string ERR_NOADMININFO() { return ("<server> :<reason>"); };
			/* "424" */ std::string ERR_FILEERROR() { return (":<reason>"); };
			/* "431" */ std::string ERR_NONICKNAMEGIVEN() { return (":<reason>"); };
			/* "432" */ std::string ERR_ERRONEUSNICKNAME() { return ("<nick> :<reason>"); };
			/* "433" */ std::string ERR_NICKNAMEINUSE() { return ("<nick> :<reason>"); };
			/* "436" */ std::string ERR_NICKCOLLISION() { return ("<nick> :<reason>"); };
			/* "437" */ std::string ERR_UNAVAILRESOURCE() { return ("<nick/channel/service> :<reason>"); };
			/* "441" */ std::string ERR_USERNOTINCHANNEL() { return ("<nick> <channel> :<reason>"); };
			/* "442" */ std::string ERR_NOTONCHANNEL() { return ("<channel> :<reason>"); };
			/* "443" */ std::string ERR_USERONCHANNEL() { return ("<nick> <channel> [:<reason>]"); };
			/* "444" */ std::string ERR_NOLOGIN() { return ("<user> :<reason>"); };
			/* "445" */ std::string ERR_SUMMONDISABLED() { return (":<reason>"); };
			/* "446" */ std::string ERR_USERSDISABLED() { return (":<reason>"); };
			/* "451" */ std::string ERR_NOTREGISTERED() { return (":<reason>"); };
			/* "461" */ std::string ERR_NEEDMOREPARAMS() { return ("<command> :<reason>"); };
			/* "462" */ std::string ERR_ALREADYREGISTRED() { return (":<reason>"); };
			/* "463" */ std::string ERR_NOPERMFORHOST() { return (":<reason>"); };
			/* "464" */ std::string ERR_PASSWDMISMATCH() { return (":<reason>"); };
			/* "465" */ std::string ERR_YOUREBANNEDCREEP() { return (":<reason>"); };
			/* "467" */ std::string ERR_KEYSET() { return ("<channel> :<reason>"); };
			/* "471" */ std::string ERR_CHANNELISFULL() { return ("<channel> :<reason>"); };
			/* "472" */ std::string ERR_UNKNOWNMODE() { return ("<char> :<reason>"); };
			/* "473" */ std::string ERR_INVITEONLYCHAN() { return ("<channel> :<reason>"); };
			/* "474" */ std::string ERR_BANNEDFROMCHAN() { return ("<channel> :<reason>"); };
			/* "475" */ std::string ERR_BADCHANNELKEY() { return ("<channel> :<reason>"); };
			/* "476" */ std::string ERR_BADCHANMASK() { return ("<channel> :<reason>"); };
			/* "477" */ std::string ERR_NOCHANMODES() { return ("<channel> :<reason>"); };
			/* "478" */ std::string ERR_BANLISTFULL() { return ("<channel> <char> :<reason>"); };
			/* "481" */ std::string ERR_NOPRIVILEGES() { return (":<reason>"); };
			/* "482" */ std::string ERR_CHANOPRIVSNEEDED() { return ("<channel> :<reason>"); };
			/* "483" */ std::string ERR_CANTKILLSERVER() { return (":<reason>"); };
			/* "484" */ std::string ERR_RESTRICTED() { return (":<reason>"); };
			/* "485" */ std::string ERR_UNIQOPRIVSNEEDED() { return (":<reason>"); };
			/* "491" */ std::string ERR_NOOPERHOST() { return (":<reason>"); };
			/* "501" */ std::string ERR_UMODEUNKNOWNFLAG() { return (":<reason>"); };
			/* "502" */ std::string ERR_USERSDONTMATCH() { return (":<reason>"); };
	};

	#endif